CC=gcc
CFLAGS=-std=c11 -Wpedantic -Wall -Wextra
LDLIBS=-lm
RM=rm -f
OBJ=ex1.o matrice.o
EXE=ex1
# Pour produire le fichier exécutable
$(EXE):$(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(EXE) $(LDLIBS)
# Pour produire les fichiers objets
ex1.o:ex1.c matrice.h
	$(CC) $(CFLAGS) -c ex1.c
matrice.o:matrice.c matrice.h
	$(CC) $(CFLAGS) -c matrice.c
# Pour effacer les objets et les exécutables
clean:
	$(RM) $(OBJ) $(EXE) 